#!/bin/bash

#SBATCH -p rome16q           # partition (queue)
#SBATCH -N 1                # number of nodes
#SBATCH --ntasks-per-node 1 # number of cores
#SBATCH -t 0-00:01          # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out  # STDOUT
#SBATCH -e slurm.%N.%j.err  # STDERR
#SBATCH --exclusive

module purge
module load openmpi4/gcc/4.1.2

mpirun -np $SLURM_NTASKS --bind-to none build/debug/csr /home/krisor99/UiB-INF339/matrices/Hamrle1.mtx
