#!/bin/bash
#SBATCH -p rome16q # partition (queue)
#SBATCH -N 2
#SBATCH --ntasks 2   # number of cores
#SBATCH -t 0-4:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --exclusive


module purge
module load openmpi-4.0.5
module load boost-mpi-1.73.0
module load boost-1.73.0
module load slurm/21.08.8
module load libfabric/gcc/1.18.0
module load openmpi4/gcc/4.1.2
module load libevent/2.1.12-stable
module load cuda11.8/toolkit/11.8.0

srun build/debug/csr "/home/krisor99/BrakeCommunicator/csr/matrices/Hamrle1.mtx"
srun build/debug/csr "/home/krisor99/BrakeCommunicator/csr/matrices/Hamrle1.mtx"
